### PR TITLE
Added fs usage example

### PR DESCRIPTION
**Pull request by roobre**
The FS API seems quite important to me, but there was no example available, so I made this one.

I mostly guessed the program structure from the function names and types, so perhaps its not the most optimal way of doing it. Please don't hesitate to correct me if that's the case.

### CODE REVIEW

**Comment by fincs** [comment]
Normal applications should use the standard C api, which is fully functional (including opendir and friends).

**Comment by roobre** [comment]
I mostly wanted to get the feel on how services work. Should I clarify this is not the normal way of doing it somewhere?

**Comment by fincs** [comment]
If we have an example of how to use the fsp-srv API directly, people will copypaste it and avoid using the standard C api (which is what should be used in most cases).

**Comment by roobre** [comment]
Ouch, then I guess there is no room for this. Feel free to close if you guys think it's better that way.

**Comment by yellows8** [comment]
We should have a FS stdio example, not this. Which should go under "/fs/{name}/" like this one does (already have a local example for something else at "/fs/{name}/").

Normally fs.h funcs shouldn't be called by apps, unless the output is being passed to fs_dev/romfs_dev for mounting.

**Pull request closed without merging**
