### PR TITLE
Add license for Github

### PR DESCRIPTION
**Pull request by tron-pixel-2**
As pointed out in #57 , this repo was made under the public domain about a month ago. I missed this in my comment and apologize for that. I did not see the small image at the bottom of the readme.

I don't think you had to go as far as censoring my comment or blocking me from contributing to the org, but to prevent this situation in the future, this LICENSE file in this PR should show up in the Github UI.

Thanks again

### CODE REVIEW

**Comment by fincs** [comment]
README files are supposed to be read. The README clearly states that the example code is under Public Domain, as explained by Creative Commons. Therefore, it is not necessary to clarify anything further.

**Comment by tron-pixel-2** [comment]
This PR is for it to show up in the Github UI, like the other projects in this org: licenses

**Comment by fincs** [comment]
Public Domain isn't really a license granted to the user by its copyright holder. It basically surrenders any claim of copyright to the work, therefore allowing anyone to use it without any restriction.

And for reference, a block was preemptively applied on your username because we get far too many license trolls that make a lot of noise about complete non-issues, and this is now our standard policy. We can get you unblocked if your intention wasn't to deliberately spread misinformation about devkitPro and organizations associated with devkitPro, though.

**Comment by tron-pixel-2** [comment]
I agree with what you're saying, and I definitely missed that when viewing the Readme. I also understand the desire to leave out a formal license now after reading about [Public domain mark](https://en.wikipedia.org/wiki/Public_Domain_Mark).

I shouldn't have jumped the gun because I saw no license in Github UI, and also shouldn't have assumed certain things based on what I saw in other places, and again I'm sorry for that.

There might be a future where I'd be interested in adding more to the readme about what dependencies are needed to build different switch-examples projects, as I'm currently running into some confusion about that. Would contributions like this be appreciated?

**Comment by fincs** [comment]
Thank you for your understanding. I've gone ahead and unblocked your username.

PRs improving the documentation, especially in the area concerning which packages need to be installed for which examples, would be welcome. There's already [a few examples](https://github.com/switchbrew/switch-examples/tree/master/graphics/opengl) which have readmes of their own stating which packages you need to install.

**Pull request closed without merging**
